### ISSUE TITLE
Use enums to define different browsers in the command line while running the tests.

### ISSUE THREAD

**Issue by tkvarma-tw** [dsahu-tw/UIAutomation#1]
Issue 1: 

Use Enums in the framework instead of using if-else expression in "Driver.java" as part of the clean code strategy. Define different browsers in separate enum file (just as you did for element state like Clickable,Visible,Presence etc)and call that enum in the Driver.java.

Issue 2:

Try to define the capability of defining browsers as part of maven command instead of config.properties file as it makes the browsers execution as loosely coupled to the framework.

**Comment by biswajit-713** [comment]
Issue 1: alternatively you can use suppliers to get the browser driver from a map. that will avoid if, else

Issue 2: adding to the above, you may make config.properties as your default. so if the command line does the provide those params, you take it from config.properties

**Comment by dsahu-tw** [comment]
> Issue 1:
> 
> Use Enums in the framework instead of using if-else expression in "Driver.java" as part of the clean code strategy. Define different browsers in separate enum file (just as you did for element state like Clickable,Visible,Presence etc)and call that enum in the Driver.java.
> **[used switch as discussed in the call]**
> Issue 2:
> 
> Try to define the capability of defining browsers as part of maven command instead of config.properties file as it makes the browsers execution as loosely coupled to the framework.
**[Done, please refer readme file for commands]**
