### ISSUE TITLE
static instead of instance

### ISSUE THREAD

**Issue by biswajit-713** [dsahu-tw/UIAutomation#4]
in Driver.class do you really want to use static Driver? why not create an instance. also is it possible to avoid Thread.sleep.

does it allow now to run tests in parallel?

**Comment by dsahu-tw** [comment]
Removed thread.sleep
Yes parallel execution is allowed
For 'static Driver' I will connect with you can not see it in code.

**Comment by dsahu-tw** [comment]
Hi @biswajit-713 
Please ping the file name and line number where 'static Driver' has been used.
Also please ping in google chat. I am unable to search you on chat.
Thanks

**Comment by dsahu-tw** [comment]
closing the ticket. there is no static driver in the code.
