### ISSUE TITLE
Command for running test given in ReadMe file seems wrong

### ISSUE THREAD

**Issue by rahul-kumar-sdet** [dsahu-tw/UIAutomation#5]
Hi,
The command for running all tests specified in Readme file seems to be incorrect , can you double check?

- Command as per readme - mvn clean test -pAll

- **Error**  - Unable to parse command line options: Unrecognized option: -pAll

**Comment by dsahu-tw** [comment]
The command seems correct. Please try again, if does not work then we can connect.
PFA

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/108712449/198016063-27a173c9-40cf-4599-92e9-12079302f75d.png">

**Comment by rahul-kumar-sdet** [comment]
Hey Deepak, The command should contain **capital P** instead of **small p** . Rest all is okay :)

**Comment by dsahu-tw** [comment]
oh..ok
Thank, I will update readme file
